### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaGizmos/InteractNext.jl#10]
I don't understand the issue but it might be hitting some sort of rollback issue with npm in `NodeJS`. 

If I install `popper` it seems to get removed again. But I am not sure that is really the cause of the error.

The issue arises when:
```julia
julia> using WebIO

julia> WebIO.devsetup()
INFO: Installing NodeJS v0.4.0
INFO: Building NodeJS
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN bootstrap@4.0.0 requires a peer of popper.js@^1.12.9 but none is installed. You must install peer dependencies yourself.
npm WARN abradley@1.0.0 No description
npm WARN abradley@1.0.0 No repository field.

+ webpack-cli@2.0.11
+ webpack@4.1.1
updated 2 packages in 23.355s
INFO: Removing NodeJS v0.4.0

julia> WebIO.bundlejs(watch=false)
INFO: Installing NodeJS v0.4.0
INFO: Building NodeJS
up to date in 2.399s
module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/abradley/.julia/v0.6/WebIO/deps/node_modules/webpack-cli/bin/webpack.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
ERROR: LoadError: failed process: Process(`/Users/abradley/.julia/v0.6/NodeJS/deps/bin/node-v8.10.0-darwin-x64/bin/node ../../deps/node_modules/webpack-cli/bin/webpack.js`, ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [5] #bundlejs#42(::Bool, ::Function) at /Users/abradley/.julia/v0.6/WebIO/src/devsetup.jl:12
 [6] (::WebIO.#kw##bundlejs)(::Array{Any,1}, ::WebIO.#bundlejs) at ./<missing>:0
while loading /Users/abradley/.julia/v0.6/WebIO/deps/_bundlejs.jl, in expression starting on line 22
```

**Comment by AshtonSBradley** [comment]
```julia
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by AshtonSBradley** [comment]
It gets slightly further now:
```julia
julia> using WebIO

julia> WebIO.devsetup()
INFO: Installing NodeJS v0.4.0
INFO: Building NodeJS
npm WARN saveError ENOENT: no such file or directory, open '/Users/abradley/.julia/v0.6/WebIO/deps/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/abradley/.julia/v0.6/WebIO/deps/package.json'
npm WARN deps No description
npm WARN deps No repository field.
npm WARN deps No README data
npm WARN deps No license field.

+ webpack-cli@2.0.11
+ webpack@4.1.1
updated 2 packages in 3.402s
INFO: Removing NodeJS v0.4.0

julia> WebIO.bundlejs(watch=false)
INFO: Installing NodeJS v0.4.0
INFO: Building NodeJS
up to date in 1.152s
Hash: 2084287febec75651ad76ed82a47cc5a2aa8ed7f
Version: webpack 4.1.1
Child
    Hash: 2084287febec75651ad7
    Time: 303ms
    Built at: 2018-3-13 09:00:44
        Asset     Size  Chunks             Chunk Names
    bundle.js  128 KiB       0  [emitted]  bundle
    Entrypoint bundle = bundle.js
       [0] (webpack)/buildin/global.js 509 bytes {0} [built]
       [1] ./webio.js 6.42 KiB {0} [built]
       [9] ./node.js 10.5 KiB {0} [built]
      [12] ./unsafe_script.js 1.49 KiB {0} [built]
      [13] ./index.js 90 bytes {0} [built]
        + 9 hidden modules
Child
    Hash: 6ed82a47cc5a2aa8ed7f
    Time: 257ms
    Built at: 2018-3-13 09:00:44
                        Asset      Size  Chunks             Chunk Names
    webcomponents-lite.min.js  83.1 KiB       0  [emitted]  webcomponents-lite.min
    Entrypoint webcomponents-lite.min = webcomponents-lite.min.js
       [1] (webpack)/buildin/global.js 509 bytes {0} [built]
        + 2 hidden modules
INFO: Removing NodeJS v0.4.0

julia> using InteractNext
INFO: Recompiling stale cache file /Users/abradley/.julia/lib/v0.6/DataStructures.ji for module DataStructures.
WARNING: Module Compat with uuid 608723368644386 is missing from the cache.
This may mean module Compat does not support precompilation but is imported by a module that does.
ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
Stacktrace:
 [1] _require(::Symbol) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [2] require(::Symbol) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [3] include_from_node1(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [4] include(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [5] anonymous at ./<missing>:2
while loading /Users/abradley/.julia/v0.6/DataStructures/src/DataStructures.jl, in expression starting on line 19
ERROR: LoadError: LoadError: Failed to precompile DataStructures to /Users/abradley/.julia/lib/v0.6/DataStructures.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [6] include_from_node1(::String) at ./loading.jl:576
 [7] eval(::Module, ::Any) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [8] _require(::Symbol) at ./loading.jl:490
 [9] require(::Symbol) at ./loading.jl:405
while loading /Users/abradley/.julia/v0.6/InteractNext/src/widgets.jl, in expression starting on line 3
while loading /Users/abradley/.julia/v0.6/InteractNext/src/InteractNext.jl, in expression starting on line 7

julia> 

```

**Comment by shashi** [comment]
Seems like the `devsetup` went through fine! You don't need to run it unless you plan on developing this package. :-)

Did you try restarting Julia and trying `using InteractNext` again?

**Comment by AshtonSBradley** [comment]
yes, it goes through without error, but when I run the rainbow snake example 
```julia
using InteractNext

width, height = 700, 300
colors = ["black", "gray", "silver", "maroon", "red", "olive", "yellow", "green", "lime", "teal", "aqua", "navy", "blue", "purple", "fuchsia"]
color(i) = colors[i%length(colors)+1]
ui = @manipulate for nsamples in 1:200,
        sample_step in slider(0.01:0.01:1.0, value=0.1, label="sample step"),
        phase in slider(0:0.1:2pi, value=0, label="phase"),
        radii in 0.1:0.1:60
    cxs_unscaled = [i*sample_step + phase for i in 1:nsamples]
    cys = sin.(cxs_unscaled) .* height/3 .+ height/2
    cxs = cxs_unscaled .* width/4pi
    dom"svg:svg[width=$width, height=$height]"(
        (dom"svg:circle[cx=$(cxs[i]), cy=$(cys[i]), r=$radii, fill=$(color(i))]"()
            for i in 1:nsamples)...
    )
end
display(ui)
```
nothing appears (apart from the usual precompile info) - no sliders or graphics.

**Comment by shashi** [comment]
I think you'd need to run that in Jupyter... If you want to use Blink.jl see an example file in the example directory.

**Comment by AshtonSBradley** [comment]
yes, that was run in Jupyter (I should have said).

**Comment by AshtonSBradley** [comment]
The errors have gone in Jupyter, and it seems to run ok, but then no figure appears ...
